---

- hosts: all
  become: true
  tasks:


#Ubuntu and Debian

  - name: install apache and php package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes


