---
#use this when there are specific OS's to target

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: install apache2 package
    apt:
       name: apache2
       state: latest
    when: ansible_distribution in ["Ubuntu"]

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == ["Ubuntu"]


  - name: update repo index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    dnf:
       name: httpd
       state: latest
    when: ansible_distribution in ["CentOS"]

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == ["CentOS"]

